name = "my-one-password-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "my-one-password-db"
database_id = "local-dev-db"

# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "my-one-password-storage"
